apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy-2022bcd0036
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: flask
        image: 2022bcd0036-prathibha
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: db-config-2022bcd0036
        - secretRef:
            name: db-secret-2022bcd0036
